# Generated by Django 6.0.2 on 2026-03-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0005_alter_project_options_remove_project_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of application review.",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(
                        blank=True,
                        help_text="Free-text motivation from the applicant.",
                        verbose_name="Motivation",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when application was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the latest application update.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        help_text="Student user who submitted the application.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Applicant",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that this application targets.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="projects.project",
                        verbose_name="Project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="appl_status_created_idx"),
                    models.Index(
                        fields=["applicant", "created_at"], name="appl_applicant_created_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "applicant"),
                        name="applications_unique_project_applicant",
                    )
                ],
            },
        ),
    ]
