# Generated by Django 6.0.2 on 2026-03-08 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_application_statuses(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    Application.objects.filter(status="pending").update(status="submitted")
    Application.objects.filter(status="declined").update(status="rejected")


def rollback_legacy_application_statuses(apps, schema_editor):
    Application = apps.get_model("applications", "Application")
    Application.objects.filter(status="submitted").update(status="pending")
    Application.objects.filter(status="rejected").update(status="declined")


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="review_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Teacher/CPPRP decision comment.",
                verbose_name="Review comment",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the application review decision.",
                null=True,
                verbose_name="Reviewed at",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reviewed this application.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
        migrations.RunPython(
            migrate_legacy_application_statuses,
            rollback_legacy_application_statuses,
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="submitted",
                help_text="Current status of application review.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
