# Generated by Django 6.0.4 on 2026-04-25 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0011_initiativeproposal_initiativeproposalsubmission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultyPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_publication_id", models.CharField(max_length=255, unique=True)),
                ("title", models.TextField()),
                ("publication_type", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("created_at_source", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="FacultySyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("resource", models.CharField(max_length=100, unique=True)),
                ("cursor", models.CharField(blank=True, max_length=255)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["resource"],
            },
        ),
        migrations.CreateModel(
            name="FacultyPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_person_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("source_profile_url", models.URLField(max_length=500, unique=True)),
                ("source_key", models.CharField(max_length=255, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("full_name_normalized", models.CharField(db_index=True, max_length=255)),
                ("primary_unit", models.CharField(blank=True, max_length=255)),
                (
                    "primary_unit_normalized",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("campus_id", models.CharField(blank=True, max_length=100)),
                ("campus_name", models.CharField(blank=True, max_length=255)),
                ("publications_total", models.PositiveIntegerField(default=0)),
                ("emails", models.JSONField(blank=True, default=list)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("positions", models.JSONField(blank=True, default=list)),
                ("relations", models.JSONField(blank=True, default=dict)),
                ("research_ids", models.JSONField(blank=True, default=dict)),
                ("public_payload", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("source_seen_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("is_stale", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["full_name", "source_key"],
                "indexes": [
                    models.Index(
                        fields=["full_name_normalized", "primary_unit_normalized"],
                        name="faculty_fac_full_na_544f7f_idx",
                    ),
                    models.Index(
                        fields=["is_stale", "updated_at"], name="faculty_fac_is_stal_b0bd15_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FacultyCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("course_key", models.CharField(max_length=255, unique=True)),
                ("title", models.TextField()),
                ("url", models.URLField(blank=True, max_length=500)),
                ("academic_year", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(blank=True, max_length=100)),
                ("level", models.CharField(blank=True, max_length=100)),
                ("raw_meta", models.TextField(blank=True)),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="faculty.facultyperson",
                    ),
                ),
            ],
            options={
                "ordering": ["person_id", "-academic_year", "title"],
            },
        ),
        migrations.CreateModel(
            name="FacultyAuthorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("display_name", models.CharField(max_length=255)),
                ("href", models.URLField(blank=True, max_length=500)),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authorships",
                        to="faculty.facultyperson",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authorships",
                        to="faculty.facultypublication",
                    ),
                ),
            ],
            options={
                "ordering": ["publication_id", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("publication", "position"),
                        name="faculty_unique_authorship_position",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectFacultyMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("supervisor_name", models.CharField(blank=True, max_length=255)),
                ("supervisor_email", models.CharField(blank=True, max_length=255)),
                ("supervisor_department", models.CharField(blank=True, max_length=255)),
                ("match_strategy", models.CharField(blank=True, max_length=100)),
                ("confidence", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("ambiguous", "Ambiguous"),
                            ("unmatched", "Unmatched"),
                        ],
                        db_index=True,
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("candidate_person_ids", models.JSONField(blank=True, default=list)),
                ("matched_by", models.CharField(blank=True, default="system", max_length=100)),
                ("matched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_matches",
                        to="faculty.facultyperson",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_matches",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["project_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project",), name="faculty_unique_project_match"
                    )
                ],
            },
        ),
    ]
