# Generated by Django 6.0.4 on 2026-05-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
