# Generated by Django 6.0.2 on 2026-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("customer", "Customer"),
                            ("cpprp", "CPPRP"),
                            ("global", "Global"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PlatformDeadline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("customer", "Customer"),
                            ("cpprp", "CPPRP"),
                            ("global", "Global"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ends_at", "title"],
            },
        ),
    ]
