# Generated by Django 6.0 on 2026-01-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_project_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
