# Generated by Django 6.0.2 on 2026-03-08 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_options_remove_project_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="accepted_participants_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Current number of accepted student applications.",
                verbose_name="Accepted participants count",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the latest moderation decision.",
                null=True,
                verbose_name="Moderated at",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who made the latest moderation decision.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Moderated by",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="moderation_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reason/comment for moderation decision.",
                verbose_name="Moderation comment",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="team_size",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of students needed for this project.",
                verbose_name="Team size",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("on_moderation", "On moderation"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                    ("staffed", "Staffed"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                help_text="Publishing lifecycle state used in filters and workflows.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
