# Generated by Django 6.0.2 on 2026-03-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="content",
        ),
        migrations.RemoveField(
            model_name="project",
            name="price",
        ),
        migrations.RemoveField(
            model_name="project",
            name="public",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when project was created.",
                null=True,
                verbose_name="Created at",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Short project description and context for students.",
                verbose_name="Description",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Unstructured source-specific payload for hybrid MVP model.",
                verbose_name="Extra data",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                help_text="Project owner (mentor/customer) who created this project.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="External source identifier (sheet row key, EPP id, etc.).",
                max_length=255,
                verbose_name="Source reference",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("supervisor", "Supervisor"),
                    ("initiative", "Initiative"),
                    ("epp", "EPP"),
                    ("manual", "Manual"),
                ],
                db_index=True,
                default="manual",
                help_text="Data source of the project (sheet/import/manual).",
                max_length=20,
                verbose_name="Source type",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                db_index=True,
                default="draft",
                help_text="Publishing lifecycle state used in filters and workflows.",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Technology tags as JSON list (temporary MVP storage format).",
                verbose_name="Tech tags",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of the latest project update.",
                null=True,
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                help_text="Human-readable project title shown in catalog and API lists.",
                max_length=255,
                verbose_name="Title",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status", "created_at"], name="projects_status_created_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner", "created_at"], name="projects_owner_created_idx"),
        ),
    ]
