# Generated by Django 6.0.2 on 2026-03-15 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_accepted_participants_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        help_text="Unique EPP identifier from the source file.",
                        max_length=255,
                        unique=True,
                        verbose_name="Source reference",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True,
                        help_text="EPP title from the source file.",
                        verbose_name="Title",
                    ),
                ),
                (
                    "campaign_ref",
                    models.CharField(
                        blank=True,
                        help_text="Campaign identifier from the source file.",
                        max_length=255,
                        verbose_name="Campaign reference",
                    ),
                ),
                (
                    "campaign_title",
                    models.TextField(
                        blank=True,
                        help_text="Campaign title from the source file.",
                        verbose_name="Campaign title",
                    ),
                ),
                (
                    "created_at_source",
                    models.DateTimeField(
                        blank=True,
                        help_text="Creation timestamp from the source file.",
                        null=True,
                        verbose_name="Created at source",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Start date from the source file.",
                        null=True,
                        verbose_name="Start date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="End date from the source file.",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "supervisor_name",
                    models.CharField(
                        blank=True,
                        help_text="EPP supervisor name from the source file.",
                        max_length=255,
                        verbose_name="Supervisor name",
                    ),
                ),
                (
                    "supervisor_email",
                    models.CharField(
                        blank=True,
                        help_text="EPP supervisor email from the source file.",
                        max_length=255,
                        verbose_name="Supervisor email",
                    ),
                ),
                (
                    "supervisor_department",
                    models.CharField(
                        blank=True,
                        help_text="Supervisor department from the source file.",
                        max_length=255,
                        verbose_name="Supervisor department",
                    ),
                ),
                (
                    "initiator_name",
                    models.CharField(
                        blank=True,
                        help_text="EPP initiator from the source file.",
                        max_length=255,
                        verbose_name="Initiator name",
                    ),
                ),
                (
                    "initiator_type",
                    models.CharField(
                        blank=True,
                        help_text="EPP initiator type from the source file.",
                        max_length=255,
                        verbose_name="Initiator type",
                    ),
                ),
                (
                    "status_raw",
                    models.CharField(
                        blank=True,
                        help_text="Raw EPP status from the source file.",
                        max_length=255,
                        verbose_name="Source status",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete EPP source payload for round-trip compatibility.",
                        verbose_name="Raw payload",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when EPP record was created locally.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the latest local EPP update.",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "EPP",
                "verbose_name_plural": "EPP records",
                "ordering": ["source_ref"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="activity_type",
            field=models.CharField(
                blank=True,
                help_text="Source activity type.",
                max_length=255,
                verbose_name="Activity type",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="applications_count_source",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Current applications count from source data.",
                null=True,
                verbose_name="Applications count in source",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="co_supervisors",
            field=models.TextField(
                blank=True,
                help_text="Co-supervisors for the vacancy/topic.",
                verbose_name="Co-supervisors",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_date",
            field=models.DateField(
                blank=True,
                help_text="Contract date from source data.",
                null=True,
                verbose_name="Contract date",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_number",
            field=models.CharField(
                blank=True,
                help_text="Contract number from source data.",
                max_length=255,
                verbose_name="Contract number",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="control_form",
            field=models.CharField(
                blank=True,
                help_text="Control form from source data.",
                max_length=255,
                verbose_name="Control form",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cooperation_type",
            field=models.CharField(
                blank=True,
                help_text="Cooperation type from source data.",
                max_length=255,
                verbose_name="Cooperation type",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="credits",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Credits from source data.",
                max_digits=8,
                null=True,
                verbose_name="Credits",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="data_tools",
            field=models.TextField(
                blank=True,
                help_text="Data tools and methods from source data.",
                verbose_name="Data tools",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="digital_tools",
            field=models.TextField(
                blank=True,
                help_text="Digital tools from source data.",
                verbose_name="Digital tools",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="external_customer",
            field=models.CharField(
                blank=True,
                help_text="External customer from source data.",
                max_length=255,
                verbose_name="External customer",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="external_customer_location",
            field=models.CharField(
                blank=True,
                help_text="Location of external organization from source data.",
                max_length=255,
                verbose_name="External customer location",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="grading_formula",
            field=models.TextField(
                blank=True,
                help_text="Grading formula from source data.",
                verbose_name="Grading formula",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="hours_per_week",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Student load in hours per week from source data.",
                max_digits=8,
                null=True,
                verbose_name="Hours per week",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="implementation_features",
            field=models.TextField(
                blank=True,
                help_text="Implementation features from source data.",
                verbose_name="Implementation features",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="implementation_language",
            field=models.CharField(
                blank=True,
                help_text="Source implementation language.",
                max_length=255,
                verbose_name="Implementation language",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="inn",
            field=models.CharField(
                blank=True, help_text="INN from source data.", max_length=32, verbose_name="INN"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="internal_customer",
            field=models.CharField(
                blank=True,
                help_text="Internal customer from source data.",
                max_length=255,
                verbose_name="Internal customer",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_paid",
            field=models.BooleanField(
                blank=True,
                help_text="Whether participation is paid.",
                null=True,
                verbose_name="Is paid",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Implementation location from source data.",
                max_length=255,
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="methods",
            field=models.TextField(
                blank=True, help_text="Methods from source data.", verbose_name="Methods"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="organization_type",
            field=models.CharField(
                blank=True,
                help_text="Organization type from source data.",
                max_length=255,
                verbose_name="Organization type",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="practice_contract_status",
            field=models.CharField(
                blank=True,
                help_text="Status of practice contract from source data.",
                max_length=255,
                verbose_name="Practice contract status",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="programming_languages",
            field=models.TextField(
                blank=True,
                help_text="Programming languages from source data.",
                verbose_name="Programming languages",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="python_libraries",
            field=models.TextField(
                blank=True,
                help_text="Python libraries from source data.",
                verbose_name="Python libraries",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="raw_payload",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Complete vacancy source payload for round-trip compatibility.",
                verbose_name="Raw payload",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="results_presentation_format",
            field=models.TextField(
                blank=True,
                help_text="Results presentation and defense format from source data.",
                verbose_name="Results presentation format",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="retakes_allowed",
            field=models.BooleanField(
                blank=True,
                help_text="Whether retakes are allowed.",
                null=True,
                verbose_name="Retakes allowed",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="selection_criteria",
            field=models.TextField(
                blank=True,
                help_text="Selection criteria from source data.",
                verbose_name="Selection criteria",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="source_row_index",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="1-based row number from the original spreadsheet.",
                null=True,
                verbose_name="Source row index",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="startup_as_thesis",
            field=models.BooleanField(
                blank=True,
                help_text='Whether "Startup as thesis" is enabled in source data.',
                null=True,
                verbose_name="Startup as thesis",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="status_raw",
            field=models.CharField(
                blank=True,
                help_text="Raw vacancy status from the source file.",
                max_length=255,
                verbose_name="Source status",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="student_participation_format",
            field=models.CharField(
                blank=True,
                help_text="Student participation format from source data.",
                max_length=255,
                verbose_name="Student participation format",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="supervisor_department",
            field=models.CharField(
                blank=True,
                help_text="Supervisor department for the vacancy/topic.",
                max_length=255,
                verbose_name="Supervisor department",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="supervisor_email",
            field=models.CharField(
                blank=True,
                help_text="Supervisor email for the vacancy/topic.",
                max_length=255,
                verbose_name="Supervisor email",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="supervisor_name",
            field=models.CharField(
                blank=True,
                help_text="Supervisor name for the vacancy/topic.",
                max_length=255,
                verbose_name="Supervisor name",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="supervisor_staff_category",
            field=models.CharField(
                blank=True,
                help_text="Supervisor staff category from the source file.",
                max_length=255,
                verbose_name="Supervisor staff category",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="thesis_title",
            field=models.CharField(
                blank=True,
                help_text="Source thesis title.",
                max_length=255,
                verbose_name="Thesis title",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="thesis_title_en",
            field=models.CharField(
                blank=True,
                help_text="Source thesis title in English.",
                max_length=255,
                verbose_name="Thesis title in English",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="usage_areas",
            field=models.TextField(
                blank=True, help_text="Usage areas from source data.", verbose_name="Usage areas"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="uses_ai",
            field=models.BooleanField(
                blank=True,
                help_text="Whether AI is planned in the work.",
                null=True,
                verbose_name="Uses AI",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vacancy_initiator",
            field=models.CharField(
                blank=True,
                help_text="Vacancy initiator from source data.",
                max_length=255,
                verbose_name="Vacancy initiator",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vacancy_initiator_type",
            field=models.CharField(
                blank=True,
                help_text="Vacancy initiator type from source data.",
                max_length=255,
                verbose_name="Vacancy initiator type",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vacancy_tags",
            field=models.TextField(
                blank=True, help_text="Vacancy tags from source data.", verbose_name="Vacancy tags"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vacancy_title",
            field=models.CharField(
                blank=True,
                help_text="Source vacancy title.",
                max_length=255,
                verbose_name="Vacancy title",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="vacancy_title_en",
            field=models.CharField(
                blank=True,
                help_text="Source vacancy title in English.",
                max_length=255,
                verbose_name="Vacancy title in English",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="work_format",
            field=models.CharField(
                blank=True,
                help_text="Work format from source data.",
                max_length=255,
                verbose_name="Work format",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="App-facing project description built from source fields when available.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                help_text="Project owner (mentor/customer) who created or owns this project.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owner",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="source_ref",
            field=models.CharField(
                blank=True,
                help_text="External source identifier for the vacancy/topic row.",
                max_length=255,
                verbose_name="Source reference",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("draft", "Draft"),
                    ("revision_requested", "Revision requested"),
                    ("supervisor_review", "Supervisor review"),
                    ("on_moderation", "On moderation"),
                    ("published", "Published"),
                    ("staffed", "Staffed"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                help_text="Normalized publishing lifecycle state used in filters and workflows.",
                max_length=32,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tech_tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Normalized technology tags derived from source fields.",
                verbose_name="Tech tags",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                help_text="App-facing vacancy title shown in catalog and API lists.",
                max_length=255,
                verbose_name="Title",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="epp",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent EPP record for file-native vacancy imports.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="projects.epp",
                verbose_name="EPP",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["epp", "status"], name="projects_epp_status_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner", "status"], name="projects_owner_status_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["supervisor_email"], name="projects_supervisor_email_idx"),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_ref", ""), _negated=True),
                fields=("source_type", "source_ref"),
                name="projects_unique_source_type_ref",
            ),
        ),
    ]
