# Generated by Django 6.0.2 on 2026-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_epp_project_activity_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="application_deadline",
            field=models.DateField(
                blank=True,
                help_text="Date when the application window closes for this project.",
                null=True,
                verbose_name="Application deadline",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="application_opened_at",
            field=models.DateField(
                blank=True,
                help_text="Date when the application window opens for this project.",
                null=True,
                verbose_name="Applications open at",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="education_program",
            field=models.CharField(
                blank=True,
                help_text="Recommended education program or OP for applicants.",
                max_length=255,
                verbose_name="Education program",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="study_course",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Recommended course for applicants when known.",
                null=True,
                verbose_name="Study course",
            ),
        ),
    ]
