# Generated by Django 6.0.2 on 2026-03-28 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_projects_status_updated_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["application_opened_at"], name="projects_app_opened_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["application_deadline"], name="projects_app_deadline_idx"),
        ),
    ]
