# Generated by Django 6.0.3 on 2026-04-01 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_project_projects_app_opened_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InitiativeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Initiative topic title.", max_length=255, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed initiative proposal description.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "tech_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Technology tags specified by the proposal author.",
                        verbose_name="Tech tags",
                    ),
                ),
                (
                    "team_size",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of participants expected for the initiative topic.",
                        verbose_name="Team size",
                    ),
                ),
                (
                    "study_course",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Recommended study course for the initiative topic.",
                        null=True,
                        verbose_name="Study course",
                    ),
                ),
                (
                    "education_program",
                    models.CharField(
                        blank=True,
                        help_text="Recommended education program for the initiative topic.",
                        max_length=255,
                        verbose_name="Education program",
                    ),
                ),
                (
                    "supervisor_name",
                    models.CharField(
                        help_text="Scientific supervisor full name. Can reference a person outside the system.",
                        max_length=255,
                        verbose_name="Supervisor name",
                    ),
                ),
                (
                    "supervisor_email",
                    models.CharField(
                        blank=True,
                        help_text="Scientific supervisor email when available.",
                        max_length=255,
                        verbose_name="Supervisor email",
                    ),
                ),
                (
                    "supervisor_department",
                    models.CharField(
                        blank=True,
                        help_text="Scientific supervisor department or affiliation.",
                        max_length=255,
                        verbose_name="Supervisor department",
                    ),
                ),
                (
                    "participants",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Participants attached to the proposal, including people outside the system.",
                        verbose_name="Participants",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("on_moderation", "On moderation"),
                            ("revision_requested", "Revision requested"),
                            ("published", "Published"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current initiative proposal workflow state.",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                (
                    "latest_submission_number",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Sequential counter of moderation submissions for history tracking.",
                        verbose_name="Latest submission number",
                    ),
                ),
                (
                    "moderated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the latest moderation decision.",
                        null=True,
                        verbose_name="Moderated at",
                    ),
                ),
                (
                    "moderation_comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Latest CPPRP moderation comment.",
                        verbose_name="Moderation comment",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the initiative proposal was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the latest initiative proposal update.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the latest moderation decision.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_initiative_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Moderated by",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Student owner who authored the initiative proposal.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiative_proposals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "published_project",
                    models.OneToOneField(
                        blank=True,
                        help_text="Catalog project created from this initiative proposal after approval.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiative_proposal",
                        to="projects.project",
                        verbose_name="Published project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Initiative proposal",
                "verbose_name_plural": "Initiative proposals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InitiativeProposalSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "submission_number",
                    models.PositiveIntegerField(
                        help_text="Sequential proposal submission number.",
                        verbose_name="Submission number",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Submitted proposal snapshot preserved for history.",
                        verbose_name="Snapshot",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this revision was submitted to CPPRP.",
                        verbose_name="Submitted at",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Moderation decision for this submitted revision.",
                        max_length=20,
                        verbose_name="Decision",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="CPPRP moderation comment for this submission.",
                        verbose_name="Comment",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when moderation decision was made for this submission.",
                        null=True,
                        verbose_name="Reviewed at",
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        help_text="Initiative proposal version submitted to CPPRP.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="projects.initiativeproposal",
                        verbose_name="Proposal",
                    ),
                ),
                (
                    "published_project",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catalog project created after approval of this submission.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiative_publication_submissions",
                        to="projects.project",
                        verbose_name="Published project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="CPPRP/staff user who reviewed the submission.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_initiative_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reviewed by",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Actor who submitted this revision.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiative_proposal_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Initiative proposal submission",
                "verbose_name_plural": "Initiative proposal submissions",
                "ordering": ["submission_number"],
            },
        ),
        migrations.AddIndex(
            model_name="initiativeproposal",
            index=models.Index(fields=["owner", "status"], name="initiative_owner_status_idx"),
        ),
        migrations.AddIndex(
            model_name="initiativeproposal",
            index=models.Index(
                fields=["status", "updated_at"], name="initiative_status_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="initiativeproposalsubmission",
            index=models.Index(
                fields=["proposal", "submitted_at"], name="initiative_submission_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="initiativeproposalsubmission",
            constraint=models.UniqueConstraint(
                fields=("proposal", "submission_number"), name="initiative_submission_unique_number"
            ),
        ),
    ]
