# Generated by Django 6.0.2 on 2026-03-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("customer", "Customer"),
                            ("cpprp", "CPPRP"),
                        ],
                        db_index=True,
                        default="student",
                        help_text="Temporary MVP role for access and filtering.",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "interests",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Student interests used by search and recommendations.",
                        verbose_name="Interests",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when profile was created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the latest profile update.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The Django user account linked to this profile.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User profile",
                "verbose_name_plural": "User profiles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["role", "created_at"], name="users_role_created_idx")
                ],
            },
        ),
    ]
