# Generated by Django 6.0.2 on 2026-03-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Short description about the user.', verbose_name='Bio'),
        ),
    ]
