# Generated by Django 6.0.2 on 2026-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("aggregate_type", models.CharField(db_index=True, max_length=100)),
                ("aggregate_id", models.CharField(db_index=True, max_length=100)),
                ("source", models.CharField(default="web", max_length=100)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
