# Generated by Django 6.0.4 on 2026-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('outbox', '0001_initial'), ('outbox', '0002_outboxconsumercheckpoint')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_type', models.CharField(db_index=True, max_length=100)),
                ('aggregate_id', models.CharField(db_index=True, max_length=100)),
                ('source', models.CharField(default='web', max_length=100)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutboxConsumerCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], db_index=True, default='active', max_length=20)),
                ('last_acked_event_id', models.BigIntegerField(default=0)),
                ('last_seen_event_id', models.BigIntegerField(default=0)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_acked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['consumer'],
            },
        ),
    ]
