# Generated by Django 6.0.2 on 2026-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outbox", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxConsumerCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("consumer", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_acked_event_id", models.BigIntegerField(default=0)),
                ("last_seen_event_id", models.BigIntegerField(default=0)),
                ("last_polled_at", models.DateTimeField(blank=True, null=True)),
                ("last_acked_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["consumer"],
            },
        ),
    ]
