# Generated by Django 6.0.2 on 2026-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(default="xlsx", max_length=50)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(db_index=True, default="pending", max_length=20)),
                ("imported_by_id", models.PositiveIntegerField(blank=True, null=True)),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
